# Generated by Django 5.0.6 on 2024-06-04 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mood', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='mood.mood')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='patient.patient')),
            ],
        ),
    ]
